# rclone gui
ProxyPass /rclone/ http://localhost:5572/ nocanon
ProxyPassReverse /rclone/ http://localhost:5572/

<Location /rclone>
	ProxyHTMLEnable On
	ProxyHTMLURLMap http://localhost:5572 /rclone/
	ProxyHTMLURLMap / /rclone/

	SetOutputFilter proxy-html
	RequestHeader unset Accept-Encoding
</Location>
