# Comitup reverse proxy

RedirectMatch 302 ^/comitup$ /comitup/

ProxyPass        /comitup/ http://10.41.0.1/
ProxyPassReverse /comitup/ http://10.41.0.1/

# Comitup uses absolute URLs for these endpoints
ProxyPass /confirm http://10.41.0.1/confirm
ProxyPass /connect http://10.41.0.1/connect
ProxyPass /blink   http://10.41.0.1/blink
